### ISSUE TITLE
Date and time of event in RSVP confirmation is in GMT time

### ISSUE THREAD

**Issue by hiteshd** [fosstr/rsvp#16]
This needs to be converted into IST time.

Currently the RSVP shows

Date: 2015-04-04 10:30:00+00:00

It needs to show

Date: 2015-04-04 16:00:00 +05:30
or
Date: 4th April 2015 at 4:00 PM

**Comment by digen** [comment]
Can you give it a shot now ? 

# date

Sat Apr  4 14:44:11 IST 2015

**Comment by hiteshd** [comment]
Emails will now show

```
Date: Saturday, April 4 2015 at 04:00 PM IST
```
