### ISSUE TITLE
email reminder of event to participants

### ISSUE THREAD

**Issue by hrj** [fosstr/rsvp#6]
Not sure if this is a good idea, as it can be considered spamming.

There are two options to reduce the "spamming" accusation:
- Send reminder only to registered users.
- Have an option for notifications (for registered users).

**Comment by hiteshd** [comment]
From the beginning, it was thought that only 2 emails are sent per event. Once during RSVP, and once before the event as a reminder. To make it better, We can have a checkbox that says "Do you want to receive a reminder?"

**Comment by hiteshd** [comment]
ada5250 fixes this
