### ISSUE TITLE
Summary email to the whole group, just before the event

### ISSUE THREAD

**Issue by hrj** [fosstr/rsvp#8]
Before the event, a summary could be sent to the whole group (mailing list), without any personal details.

For example:
- Event details: Topic, Total seats available, Date & Time, Venue, etc
- Number of people attending
- Number of people not-attending (that is, they RSVPed explicitly as not attending).

**Comment by hiteshd** [comment]
This is waiting on @digen for SMTP auth for sending email

**Comment by digen** [comment]
@hiteshd Working on this.

**Comment by digen** [comment]
@hiteshd All set. pgp.mit.edu is acting up. 
![screenshot 2015-03-18 17 21 21](https://cloud.githubusercontent.com/assets/217902/6708092/4088b27e-cd93-11e4-9441-414a622d6323.png)

**Comment by digen** [comment]
@hiteshd Details sent. Let me know if you need anything else.

**Comment by hiteshd** [comment]
Adding some finer points so we are on the same page.

An email is sent in the following conditions
1. A Confirmation email is sent to the individual when RSVP is successful
2. One email to every individual is sent 24 hours before the an event as a reminder
3. A reminder about the event is sent to everyone on the mailing list at FOSSTR fosstr@fosstr.org

I find the 3rd email sort of redundant. But thats just me.

Ideas? Thoughts?

**Comment by gsama** [comment]
The 3rd email is redundant.
Can / should we have email of all registered individuals to fosstr@fosstr.org?

**Comment by digen** [comment]
Instead of the 3rd, send email about details of participants ( name, email address ) who have confirmed attendance to the mailing list ?

**Comment by hiteshd** [comment]
Alright.
@digen  - Can you verify the credentials via the script that i sent

**Comment by digen** [comment]
@hiteshd I am working on this tonight. Will update here or in the IRC if you're around.

**Comment by hiteshd** [comment]
ada5250 Should address this. However this is not tested at this point

**Comment by hiteshd** [comment]
The SMTP server seems to be acting up again

I am getting the following from the server during testing with cron

```
(535, '5.7.8 Error: authentication failed: authentication failure')
```

@digen  - Can you check again

**Comment by digen** [comment]
@hiteshd It's working for me with the same details.

**Comment by hiteshd** [comment]
It worked for me previously too. Could you perhaps check the logs for the SMTP server. This seems to be sporadic.

**Comment by digen** [comment]
@hiteshd A small suggestion, as and when you're done, you can post the RSVP link here as well as in the mailing list for members to test the email functionality.

**Comment by hiteshd** [comment]
@digen  - Agreed!
Lets beta test this for the upcoming meetup
